TKINTER_DEFAULT_FONT_SIZE = 8
TKINTER_DEFAULT_FONT = "TkDefaultFont"
TKINTER_DEFAULT_FONT_FAMILY = "Myriad Pro SmBd"
TKINTER_DEFAULT_FONT_COLOUR = 

TKINTER_DEFAULT_COLOUR_BACKGROUND2 = "gray22"
TKINTER_DEFAULT_COLOUR_BACKGROUND1 = "gray40"
TKINTER_DEFAULT_COLOUR_BUTTON = "gray22"

TKINTER_WINDOW_TITLE = "Spacey Node Manager"
TKINTER_WINDOW_COLOUR_BACKGROUND = TKINTER_DEFAULT_COLOUR_BACKGROUND2

# Adjust the factor here to adjust window size.
WINDOW_FACTOR = 1.3

TKINTER_WINDOW_DEFAULT_WIDTH = 1280 * WINDOW_FACTOR
TKINTER_WINDOW_DEFAULT_HEIGHT = 720 * WINDOW_FACTOR

TKINTER_WIDGET_MAP_WIDTH = TKINTER_WINDOW_DEFAULT_WIDTH / 1.78
TKINTER_WIDGET_MAP_HEIGHT = TKINTER_WINDOW_DEFAULT_HEIGHT
TKINTER_WIDGET_MAP_COLOUR_BACKGROUND = TKINTER_DEFAULT_COLOUR_BACKGROUND1
TKINTER_WIDGET_MAP_TEXT_TITLE = "Map"

TKINTER_WIDGET_CONFIG_PANEL_WIDTH = TKINTER_WINDOW_DEFAULT_WIDTH / 2.5
TKINTER_WIDGET_CONFIG_PANEL_HEIGHT = TKINTER_WIDGET_MAP_HEIGHT
TKINTER_WIDGET_CONFIG_PANEL_TEXT_TITLE = "Configurations"
TKINTER_WIDGET_CONFIG_PANEL_COLOUR_BACKGROUND = TKINTER_DEFAULT_COLOUR_BACKGROUND1

TKINTER_WIDGET_DEFAULT_PADX = 20
TKINTER_WIDGET_DEFAULT_PADY = 20

TKINTER_WIDGET_CONFIG_MENU_LABELFRAME_COLOUR_BACKGROUND = TKINTER_DEFAULT_COLOUR_BACKGROUND1
TKINTER_CONFIG_MENU_FRAME_COLOUR_BACKGROUND = TKINTER_DEFAULT_COLOUR_BACKGROUND1

TKINTER_WIDGET_LEFT_MENU_TEXT_TITLE = "Menu 1"
TKINTER_WIDGET_LEFT_MENU_COLOUR_BACKGROUND = TKINTER_DEFAULT_COLOUR_BACKGROUND1
TKINTER_WIDGET_LEFT_MENU_WIDTH = TKINTER_WIDGET_CONFIG_PANEL_WIDTH / 2.2
TKINTER_WIDGET_LEFT_MENU_HEIGHT = TKINTER_WIDGET_CONFIG_PANEL_HEIGHT

TKINTER_WIDGET_RIGHT_MENU_TEXT_TITLE = "Menu 2"
TKINTER_WIDGET_RIGHT_MENU_COLOUR_BACKGROUND = TKINTER_DEFAULT_COLOUR_BACKGROUND1
TKINTER_WIDGET_RIGHT_MENU_WIDTH = TKINTER_WIDGET_CONFIG_PANEL_WIDTH / 2.2
TKINTER_WIDGET_RIGHT_MENU_HEIGHT = TKINTER_WIDGET_CONFIG_PANEL_HEIGHT


