TKINTER_DEFAULT_FONT_SIZE = 8
TKINTER_DEFAULT_FONT = "TkDefaultFont"
TKINTER_DEFAULT_FONT_FAMILY = "Myriad Pro SmBd"

TKINTER_WINDOW_TITLE = "Spacey Node Manager"
TKINTER_WINDOW_COLOUR_BACKGROUND = "gray22"

TKINTER_WINDOW_DEFAULT_WIDTH = 1280 * 1.2
TKINTER_WINDOW_DEFAULT_HEIGHT = 720 * 1.2

TKINTER_WIDGET_MAP_WIDTH = TKINTER_WINDOW_DEFAULT_WIDTH / 1.78
TKINTER_WIDGET_MAP_HEIGHT = TKINTER_WINDOW_DEFAULT_HEIGHT
TKINTER_WIDGET_MAP_COLOUR_BACKGROUND = "gray40"
TKINTER_WIDGET_MAP_TEXT_TITLE = "Map"

TKINTER_WIDGET_CONFIG_PANEL_WIDTH = TKINTER_WINDOW_DEFAULT_WIDTH / 2.5
TKINTER_WIDGET_CONFIG_PANEL_HEIGHT = TKINTER_WIDGET_MAP_HEIGHT
TKINTER_WIDGET_CONFIG_PANEL_TEXT_TITLE = "Configurations"
TKINTER_WIDGET_CONFIG_PANEL_COLOUR_BACKGROUND = "gray40"

TKINTER_WIDGET_DEFAULT_PADX = 20
TKINTER_WIDGET_DEFAULT_PADY = 20

TKINTER_WIDGET_CONFIG_MENU_LABELFRAME_COLOUR_BACKGROUND = "gray40"
TKINTER_CONFIG_MENU_FRAME_COLOUR_BACKGROUND = "gray40"


