TKINTER_DEFAULT_FONT_SIZE = 8
TKINTER_DEFAULT_FONT = "TkDefaultFont"
TKINTER_WINDOW_TITLE = "Spacey Node Manager"
TKINTER_WINDOW_COLOUR_BACKGROUND = "gray22"

TKINTER_WINDOW_DEFAULT_WIDTH = 1280
TKINTER_WINDOW_DEFAULT_HEIGHT = 720
TKINTER_WIDGET_MAP_HEIGHT = 720
TKINTER_WIDGET_MAP_WIDTH = 720
TKINTER_WIDGET_CONFIG_PANEL_WIDTH = 800
TKINTER_WIDGET_CONFIG_PANEL_HEIGHT = 1000
TKINTER_WIDGET_MAP_COLOUR_BACKGROUND = "gray40"
TKINTER_WIDGET_MAP_TEXT_TITLE = "Map"
